services:
  postgres:
    image: postgres:16-alpine
    container_name: modelrisk-postgres

    environment:
      POSTGRES_DB: modelrisk_db
      POSTGRES_USER: modelrisk_user
      POSTGRES_PASSWORD: modelrisk_password

    ports:
      - "5437:5432"

    volumes:
      - modelrisk_postgres_data:/var/lib/postgresql/data

    healthcheck:
      test:
        - CMD-SHELL
        - pg_isready -U modelrisk_user -d modelrisk_db
      interval: 10s
      timeout: 5s
      retries: 5

  adminer:
    image: adminer:latest
    container_name: modelrisk-adminer

    depends_on:
      postgres:
        condition: service_healthy

    ports:
      - "8086:8080"

volumes:
  modelrisk_postgres_data: