package com.example.modelrisk.enums;

public enum AuditEventType {
    ORGANIZATION_REGISTERED,
    USER_REGISTERED,
    MODEL_REGISTERED,
    MODEL_VERSION_CREATED,
    MODEL_VERSION_SUBMITTED,
    EVALUATION_STARTED,
    EVALUATION_COMPLETED,
    EVALUATION_FAILED,
    FINDING_CREATED,
    REVIEW_SUBMITTED,
    MODEL_VERSION_APPROVED,
    MODEL_VERSION_REJECTED,
    MODEL_VERSION_DEPLOYED,
    MODEL_VERSION_RETIRED
}